[package]
name = "tg-gpt-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Shared 
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
dotenv = "0.15.0"

# To run the Telegram bot with teloxide
teloxide = { version = "0.11", features = ["macros"] }
pretty_env_logger = "0.4"
log = "0.4.17"

# Open AI integration via HTTPS REST API
hyper = { version = "0.14.25", features = ["full"]}
hyper-tls = "0.5.0"
serde = "1.0.158"
serde_derive = "1.0.150"
serde_json = "1.0.89"
url = "2.3.1"
