[package]
name = "tg-gpt-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Shared
tokio = { version = "1.34.0", features = ["rt-multi-thread", "macros"] }
dotenv = "0.15.0"
anyhow = "1.0.78"

# To run the Telegram bot with teloxide
teloxide = { version = "0.12", features = ["macros"] }
pretty_env_logger = "0.5"
log = "0.4.20"

# Open AI integration via HTTPS REST API
hyper = { version = "1.0.1", features = ["full"] }
hyper-tls = "0.5.0"
serde = "1.0.193"
serde_derive = "1.0.193"
serde_json = "1.0.108"
url = "2.5.0"
reqwest = "0.11.22"
