#!/bin/bash

# exit when any command fails
set -e

echo "Building release."
cargo build --release
echo "Restarting service"
sudo systemctl restart tg-bot.service
echo "Service restarted, status:"
sudo systemctl status tg-bot.service
