name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build-debug
      run: cargo build --verbose
    - name: tests
      run: cargo test --verbose
    - name: build-release
      run: cargo build --verbose --release
    - name: artifact-build
      uses: actions/upload-artifact@v3
      with: 
        name: tg-gpt-debug
        path: target/release/tg-gpt-bot
