name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: trace

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cargo-fmt
      run: cargo fmt --verbose

  test:
    runs-on: ubuntu-latest

    env:
      TELOXIDE_TOKEN: ${{ secrets.TELOXIDE_TOKEN }}
      OPEN_AI_TOKEN: ${{ secrets.OPEN_AI_TOKEN }}
      OPEN_AI_URI: ${{ secrets.OPEN_AI_URI }}

    steps:
    - uses: actions/checkout@v3
    - name: cargo-test
      run: cargo test --verbose

  build:
    runs-on: ubuntu-latest

    steps:
    - name: cargo-build
      run: cargo build --verbose --release
    - name: artifact-build
      uses: actions/upload-artifact@v3
      with:
        name: tg-gpt-bot
        path: target/release/tg-gpt-bot
